### ISSUE TITLE
Panic mit format string

### ISSUE THREAD

**Issue by matthiasbeyer** [kl4rk/rust-bmi-tue#1]
https://github.com/kl4rk/rust-bmi-tue/blob/684149bb7e7dd388f36e3991c07242a4e932f0a5/src/main.rs#L35

Du kannst `panic!()` auch mit einem Format-String aufrufen, genauso wie man `println!()` aufruft!

**Comment by kl4rk** [comment]
Thanks for the suggestion, implemented!
